name: InventoryShrinks
main: me.EthanBilbrey.InventoryShrinks.Main
version: 1.0
api-version: 1.16
author: Ethan Bilbrey
description: Player inventory shrinks over time.
commands:
   isstart: 
      usage: /<command>
      description: start the challenge